function A_x = Ax(theta,phi,psi,lambda)
% coordinate transform: Azimuth, Altitute, Latitude, Longitude -> Cartesian
A_x = - cos(lambda)*cos(psi)*sin(theta)*cos(phi) ...
      - cos(lambda)*sin(psi)           *sin(phi) ...
      + sin(lambda)         *cos(theta)*cos(phi);