function A_y = Ay(theta,phi,psi,lambda)
% coordinate transform: Azimuth, Altitute, Latitude, Longitude -> Cartesian
A_y = - cos(lambda)*cos(psi)*sin(theta)*sin(phi) ...
      + cos(lambda)*sin(psi)           *cos(phi) ...
      + sin(lambda)         *cos(theta)*sin(phi);